Redirect the logo to Homepage
shescoding/projects-platform-frontend pull request #142
Opened 2020-10-01 22:50 UTC by TabithaKavyu

Header: Redirect the logo to Homepage #101

2020-10-21 01:57 UTC, nurmerey commented
@ctran14 this one addressed #101

2020-10-25 17:43 UTC, ceyuen requested changes

2020-10-25 17:44 UTC, ceyuen commented on src/components/Header.tsx
> +          <Link to="/welcome">
Sorry, it's so late! I thought I left a comment already, but missed a step to actually post it.

2020-10-28 01:46 UTC, nurmerey commented
Looks like this has already been added in #156.

2020-10-28 01:46 UTC, closed without merging