Looking for dropdown
shescoding/projects-platform-frontend pull request #151
Opened 2020-10-02 01:40 UTC by nadyafebi

Change the Looking For field of the Project Form to use Creatable from `react-select`. Closes #100.

**Changes**
* Added `react-select` as dependency.
* Change the field to use `Creatable` component.
* Added new function `handleCreatableChange` to help handle changes from `Creatable` component.
* Modified the `validateForm` function to handle `null` value.
* Modified the `handleSubmit` function to format the field value from array to comma-separated string.
* Style the field as best as I can to look similar to the other fields.

**Demo**

<img height="500" src="https://user-images.githubusercontent.com/19828938/94879514-426a0200-0415-11eb-9fc0-5384d477a8b6.gif">

2020-10-02 23:19 UTC, nurmerey requested changes
Asked for a few minor changes! Otherwise LGTM 🙌  ! Thank you @nadyafebi

2020-10-02 23:19 UTC, nurmerey commented on package.json
> +    "react-select": "^3.1.0",
Please remove `^`. This ensures that we lock in the library version and don't accidentally cause any issues down the line.

2020-10-02 23:19 UTC, nurmerey commented on src/pages/AddProject.tsx
> +  lookingForOptions: FormOptions = [
Let's add a comment at the top that these values will be coming in from a getPosition API when #114 is implemented.

2020-10-03 00:04 UTC, nadyafebi commented
@nurmerey I changed the stuff you mentioned 😄

2020-10-07 02:15 UTC, nurmerey requested changes
One more ask, to remove `yarn.lock` file. Thank you!

2020-10-07 02:15 UTC, nurmerey commented on yarn.lock
> +"@babel/runtime@^7.4.4", "@babel/runtime@^7.5.5", "@babel/runtime@^7.7.2", "@babel/runtime@^7.8.7":
`yarn.lock` should be in your `.gitignore` file, and should not be committed. Can you please remove this file from this PR? Everything else looks good!

2020-10-07 19:14 UTC, nadyafebi commented
@nurmerey Removed the yarn.lock (not sure how it got committed there) and also resolved some merge conflict 😃

2020-10-22 02:14 UTC, nadyafebi commented
Hi @nurmerey @ctran14, I saw someone else got assigned to issue #100. Should I just close this PR then? Thanks

2020-10-28 01:35 UTC, nurmerey commented
> Hi @nurmerey @ctran14, I saw someone else got assigned to issue #100. Should I just close this PR then? Thanks

Hey sorry for the mixup, the PR looks good. I will approve and merge it (and reassign the task for you!).

2020-10-28 01:37 UTC, nurmerey approved these changes
LGTM 💐 Thank you for great work!

2020-10-28 01:38 UTC, merged